Squashed commit of the following:
commit 0b3221c5fc7ea8e0509e125717599bc23efa84af
Author: getBoolean <danielwnewville@gmail.com>
Date:   Sun Aug 15 23:36:04 2021 -0500

    Remove code related to the hard coded image domain, bump version number

commit c6977c79dcf7d5c68afa971dad78499d22877d4b
Author: getBoolean <danielwnewville@gmail.com>
Date:   Sun Aug 15 23:19:39 2021 -0500

    Fixed the chapter images breaking if the image domain changes #48

commit a535dc4c1f3e1c2888c2e51d99260a95be419635
Merge: f0ab92f cbeb62d
Author: getBoolean <danielwnewville@gmail.com>
Date:   Sun Aug 15 15:31:18 2021 -0500

    Merge remote-tracking branch 'upstream/promises' into promises

commit f0ab92fd05927a741e0cdff0d4827519c5a73b00
Author: getBoolean <danielwnewville@gmail.com>
Date:   Sun Aug 15 15:30:13 2021 -0500

    Fixed titles having "漫画免费阅读全集-百年漫画" at the end of each manga details title #48

commit cd0057de338e3842014fb934afe55fbfccc7f3d0
Merge: b1d5a62 11a2011
Author: getBoolean <danielwnewville@gmail.com>
Date:   Sun Mar 28 18:35:52 2021 -0500

    Merge pull request #3 from Paperback-iOS/promises

    BainianManga: Chinese chapter numbers, reformat getHomePageSections f…

commit b1d5a62cdf63d7eacc6fdbc1369fe39d30e5e369
Merge: c859d43 1350bb3
Author: getBoolean <danielwnewville@gmail.com>
Date:   Sun Mar 28 18:27:40 2021 -0500

    Merge pull request #2 from getBoolean/Lelmangavf

    Lelmangavf

commit 1350bb3711be2a3a3221e817f8ed3e01c6b328f2
Author: getBoolean <danielwnewville@gmail.com>
Date:   Sun Mar 28 13:36:40 2021 -0500

    Fixed misnamed function

    getCloudflareBypassRequest probably isnt needed, but it doesnt hurt to have it

commit 953dc6f163eb7f876568d4e07772a8abdcfcebac
Author: Boolean <danielwnewville@gmail.com>
Date:   Mon Mar 22 01:53:26 2021 -0500

    Update version number for promises release

commit 4ed288d17ae6da60804ab0e9ee6671765a2f7cb2
Author: Boolean <danielwnewville@gmail.com>
Date:   Mon Mar 22 01:51:08 2021 -0500

    Fix missing argument

commit b7f8cdefb324cd321075b0f47107136e33b06ba6
Merge: 7980c4c c859d43
Author: Boolean <danielwnewville@gmail.com>
Date:   Mon Mar 22 01:46:11 2021 -0500

    Merge branch 'promises' into Lelmangavf

commit 7980c4c4a695c62d3b9213b747e1820740a05b34
Author: Boolean <danielwnewville@gmail.com>
Date:   Mon Mar 22 01:45:34 2021 -0500

    Fix latest manga not showing up in view more after opening a manga and hitting back

commit c859d43fa38fe3a38a462e3e6cfe9e576b30b83d
Merge: 3e9582f be0db6b
Author: getBoolean <danielwnewville@gmail.com>
Date:   Mon Mar 22 00:52:35 2021 -0500

    Merge pull request #1 from Paperback-iOS/promises

    BainianManga: change icon to png (#9)

commit 530cbb263c88224a0161283ac02844e33ce63c83
Author: Boolean <danielwnewville@gmail.com>
Date:   Sun Mar 21 17:29:59 2021 -0500

    Fixed notifications

commit 7c70978dda2d13410c34d03b68c28699cd52f36e
Author: Boolean <danielwnewville@gmail.com>
Date:   Sun Mar 21 17:29:33 2021 -0500

    Commenting out search, search test wrapper is broken

commit ba1ad9f0441996d1dddf4c81d83fb5e361527e45
Author: Boolean <danielwnewville@gmail.com>
Date:   Sun Mar 21 17:28:45 2021 -0500

    Categories are now also added to tags

commit 3efcbe5776e695736de520e61959014f58e6577b
Author: Boolean <danielwnewville@gmail.com>
Date:   Sun Mar 21 15:04:51 2021 -0500

    Fix collectedIds not resetting when calling the homepage

commit bc1a26a8ddf86e26499e12b49af125217e435c9c
Author: Boolean <danielwnewville@gmail.com>
Date:   Sun Mar 21 15:04:20 2021 -0500

    Fix chapter release date

commit cdd10f15a0732110e48b7fb38fc416a3bd702c81
Author: Boolean <danielwnewville@gmail.com>
Date:   Sun Mar 21 14:56:09 2021 -0500

    Finally fixed search

commit c8312bbd9fd00c39de204b5b5e65563739b9a97a
Author: Boolean <danielwnewville@gmail.com>
Date:   Sun Mar 21 02:52:23 2021 -0500

    Remove metadata usage as it is not needed

commit 5efb061bc4c4c201f08547fa12f80dfa67a4490d
Author: Boolean <danielwnewville@gmail.com>
Date:   Sun Mar 21 02:48:35 2021 -0500

    Save id to variable

commit 04a26251631707306cf48e4aa4c47b1e59f88c23
Author: Boolean <danielwnewville@gmail.com>
Date:   Sun Mar 21 02:43:29 2021 -0500

    Fixed json error

    Search still not working. Need to investigate

commit e0976a8949818116184d476adb6a34c5f0f08db7
Author: Boolean <danielwnewville@gmail.com>
Date:   Sun Mar 21 02:15:21 2021 -0500

    Comment out metadata, cheerio.load

    Fixes:
    TypeError: content.forEach is not a function

    New error:
    SyntaxError: Unexpected token o in JSON at position 1

    At the same line I think

commit 5f157887ef47b563b0e01dffb24e3d6b7cd93553
Author: Boolean <danielwnewville@gmail.com>
Date:   Sun Mar 21 01:36:28 2021 -0500

    Working on search

    search still not working

commit e93fe58733e48540f6b1a416af95d6f1c0828b9f
Author: Boolean <danielwnewville@gmail.com>
Date:   Sun Mar 21 01:36:00 2021 -0500

    Update parse tags to use ids and labels separately

commit add02968d1f4e9d1d77e5bbbb19658e91571345a
Author: Boolean <danielwnewville@gmail.com>
Date:   Sun Mar 21 01:35:32 2021 -0500

    Update info

commit 3eb2ddf0a884d385c1f1d9845ab4ae32b04f303f
Author: Boolean <danielwnewville@gmail.com>
Date:   Sun Mar 21 01:31:41 2021 -0500

    Test file

commit 599cda8a54bef88e0d03aa52d90f199c39648b69
Author: Boolean <danielwnewville@gmail.com>
Date:   Sat Mar 20 23:38:53 2021 -0500

    Updated tag creation to properly use ids and labels separately

commit 72f13e3fee10814b762d3e11ae4772508ddedc69
Author: Boolean <danielwnewville@gmail.com>
Date:   Sat Mar 20 04:20:25 2021 -0500

    Fix toLowerCase call

commit 4986fe1f646b205f8a080e31165462c19d138fea
Author: Boolean <danielwnewville@gmail.com>
Date:   Sat Mar 20 04:04:00 2021 -0500

    optimize search a little

commit 2c51e9af1f36ac80deaecb0def5b8517460ce59e
Author: Boolean <danielwnewville@gmail.com>
Date:   Sat Mar 20 04:00:58 2021 -0500

    Fixed viewmore only loading first page

    Known issues:
    Search not working

commit 412876ab323908a5d70d1e4d74f2ce6b68f94c13
Author: Boolean <danielwnewville@gmail.com>
Date:   Sat Mar 20 03:38:16 2021 -0500

    Lelmangavf

    Known issues:
    Search not working
    View more only loads first page